name: 'Hello New Contributors'

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello, welcome to the Project Lab! Thanks for opening your first issue."
        pr-message: "Hello, thanks for opening your first Pull Request! We will review it soon."
